# Generated by Django 6.0.5 on 2026-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('hashtable', 'Hash Table'), ('number', 'Number'), ('array', 'Array'), ('string', 'String'), ('tree', 'Tree'), ('dp', 'Dynamic Programming'), ('graph', 'Graph'), ('linkedlist', 'Linked List')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('description', models.TextField()),
                ('solution_code', models.TextField(help_text='Python solution code')),
                ('test_cases', models.JSONField(default=list, help_text='List of test inputs')),
                ('code_explanation', models.TextField(blank=True, default='', help_text='Step-by-step explanation of the solution (auto-generated or manual)')),
                ('code_explanation_hi', models.TextField(blank=True, default='', help_text='Hindi explanation (auto-generated)')),
                ('code_pattern', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
