# Generated by Django 6.0.5 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_explanation',
            field=models.TextField(blank=True, default='', help_text='Step-by-step explanation of the solution (auto-generated or manual)'),
        ),
    ]
