# Generated by Django 6.0.5 on 2026-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_problem_code_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_explanation_hi',
            field=models.TextField(blank=True, default='', help_text='Hindi explanation (auto-generated)'),
        ),
    ]
