# Generated by Django 6.0.5 on 2026-05-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_problem_code_explanation_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code_pattern',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('number', 'Number'), ('array', 'Array'), ('string', 'String'), ('tree', 'Tree'), ('dp', 'Dynamic Programming'), ('graph', 'Graph'), ('linkedlist', 'Linked List')], max_length=50),
        ),
    ]
